# Generated by Django 5.2.1 on 2025-11-23 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('requisition_date', models.DateField()),
                ('requisition_no', models.CharField(max_length=50, unique=True)),
                ('prepared_by', models.CharField(max_length=200)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PR_date', models.DateField()),
                ('PR_no', models.CharField(max_length=50)),
                ('name_of_resource', models.CharField(max_length=200)),
                ('resource_unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('team', models.CharField(choices=[('pr-manager', 'PR-Manager')], help_text='Team responsible for this requisition', max_length=50)),
                ('allow_team_edit', models.BooleanField(default=False, help_text='If True, allows the team member who created this record to edit/delete it')),
                ('edit_request_pending', models.BooleanField(default=False, help_text='If True, indicates the team member has requested edit/delete access')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this requisition record', on_delete=django.db.models.deletion.CASCADE, related_name='created_requisitions', to=settings.AUTH_USER_MODEL)),
                ('project_name_fpr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_project_name_fpr', to='project.project', verbose_name='Project Name')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this requisition record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisition Detail',
                'verbose_name_plural': 'Requisition Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequisitionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pr-manager', 'PR-Manager')], default='pr-manager', help_text="Defines the user's role in requisition manage", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requisition_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisition Role Profile',
                'verbose_name_plural': 'Requisition Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
