# Generated by Django 5.2.1 on 2025-11-21 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customerdetailed', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customerbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_bill', models.CharField(blank=True, max_length=100)),
                ('bill_date', models.DateTimeField(blank=True, help_text='Date of the bill', null=True, verbose_name='Bill Date')),
                ('bill_no', models.CharField(blank=True, max_length=20)),
                ('bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('team', models.CharField(choices=[('sm', 'SM')], help_text='Team responsible for this customerbill', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this customerbill record', on_delete=django.db.models.deletion.CASCADE, related_name='created_customerbill', to=settings.AUTH_USER_MODEL)),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Customerbill_customer_name', to='customerdetailed.customerdetailed', verbose_name='Customer Name')),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Customerbill_project_name', to='project.project', verbose_name='Project Name')),
            ],
            options={
                'verbose_name': 'Customerbill Detail',
                'verbose_name_plural': 'Customerbill Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerbillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('sm', 'SM')], default='sm', help_text="Defines the user's role in customerbill operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Customerbill_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CustomerBill Role Profile',
                'verbose_name_plural': 'CustomerBill Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
