# Generated by Django 5.2.1 on 2025-11-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerbill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbill',
            name='bill_date',
            field=models.DateTimeField(blank=True, help_text='Date of the bill', null=True, verbose_name='Bill Date'),
        ),
    ]
