# Generated by Django 5.2.1 on 2025-11-30 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_company', models.CharField(help_text='Name of the Contractor Company', max_length=100)),
                ('name_of_contractor', models.CharField(help_text='Name of the Contractor', max_length=100)),
                ('contractor_address', models.CharField(help_text='Contractor address', max_length=200)),
                ('contractor_phone_number', models.CharField(help_text='Phone number of the contractor', max_length=20)),
                ('team', models.CharField(choices=[('planner', 'Planner')], help_text='Team responsible for this contractor', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this contractor', on_delete=django.db.models.deletion.CASCADE, related_name='created_contractors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contractor',
                'verbose_name_plural': 'Contractors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('planner', 'Planner')], default='planner', help_text="Defines the user's role in contractor operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contractor Role Profile',
                'verbose_name_plural': 'Contractor Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
