# Generated by Django 5.2.1 on 2025-11-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChlorideTestReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval_min', models.IntegerField()),
                ('current_ma', models.DecimalField(decimal_places=2, max_digits=6)),
                ('voltage_v', models.DecimalField(decimal_places=2, max_digits=5)),
                ('charge_passed_coulombs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('specimen_diameter_in', models.DecimalField(decimal_places=2, max_digits=4)),
                ('chloride_ion_permeability', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
