# Generated by Django 5.2.1 on 2025-12-20 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChloridetestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('research-manager', 'Research Manager')], default='research-manager', help_text="Defines the user's role in chloride test operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chloridetest_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chloridetest Role Profile',
                'verbose_name_plural': 'Chloridetest Role Profiles',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='ChlorideTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_interval_min', models.IntegerField(help_text='Time interval in minutes')),
                ('current_ma', models.DecimalField(decimal_places=2, help_text='Measured current in milliamperes (mA)', max_digits=6)),
                ('voltage_v', models.DecimalField(decimal_places=2, help_text='Applied voltage in volts (V)', max_digits=5)),
                ('charge_passed_coulombs', models.DecimalField(decimal_places=2, help_text='Total charge passed in coulombs', max_digits=8)),
                ('specimen_diameter_in', models.DecimalField(decimal_places=2, help_text='Specimen diameter in inches', max_digits=4)),
                ('chloride_ion_permeability', models.CharField(help_text='Classification of chloride ion permeability', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks or observations')),
                ('team', models.CharField(choices=[('research-manager', 'Research Manager')], help_text='Team responsible for this chloride test', max_length=50)),
                ('allow_team_edit', models.BooleanField(default=False, help_text='If True, allows the team member who created this record to edit/delete it')),
                ('edit_request_pending', models.BooleanField(default=False, help_text='If True, indicates the team member has requested edit/delete access')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this test record', on_delete=django.db.models.deletion.CASCADE, related_name='created_chloridetests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this test record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_chloridetests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chloride Test',
                'verbose_name_plural': 'Chloride Tests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='chloridetes_created_22f506_idx'), models.Index(fields=['chloride_ion_permeability'], name='chloridetes_chlorid_e0d065_idx')],
            },
        ),
    ]
