# Generated by Django 5.2.1 on 2025-12-20 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractorbill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_address_cb', models.CharField(blank=True, max_length=200)),
                ('contractor_company_name', models.CharField(blank=True, max_length=100)),
                ('name_of_work', models.CharField(blank=True, max_length=100)),
                ('work_unit', models.CharField(choices=[('cft', 'Cft'), ('sft', 'Sft')], help_text='Unit of measurement for the work', max_length=20)),
                ('bill_date', models.DateTimeField(blank=True, help_text='Date of the bill', null=True, verbose_name='Bill Date')),
                ('bill_no', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_amount', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Auto-calculated as Quantity × Unit Price', max_digits=14)),
                ('team', models.CharField(choices=[('cm', 'CM')], help_text='Team responsible for this contractorbill', max_length=50)),
                ('allow_team_edit', models.BooleanField(default=False, help_text='If True, allows the team member who created this record to edit/delete it')),
                ('edit_request_pending', models.BooleanField(default=False, help_text='If True, indicates the team member has requested edit/delete access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this contractorbill record', on_delete=django.db.models.deletion.CASCADE, related_name='created_contractorbill', to=settings.AUTH_USER_MODEL)),
                ('project_name_cb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractorbill_project_name_cb', to='project.project', verbose_name='Project Name')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this contractorbill record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contractorbill', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contractorbill Detail',
                'verbose_name_plural': 'Contractorbill Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractorbillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('cm', 'CM')], default='cm', help_text="Defines the user's role in contractorbill operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contractorbill_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contractorbill Role Profile',
                'verbose_name_plural': 'Contractorbill Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
