# Generated by Django 5.2.1 on 2025-11-30 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(help_text='Name of the project', max_length=100)),
                ('project_address', models.CharField(help_text='Project site address', max_length=200)),
                ('contact_person_name', models.CharField(help_text='Primary contact person for the project', max_length=100)),
                ('contact_person_number', models.CharField(help_text='Phone number of the contact person', max_length=20)),
                ('team', models.CharField(choices=[('manager', 'Manager')], help_text='Team responsible for this project', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this project', on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager')], default='manager', help_text="Defines the user's role in project operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Role Profile',
                'verbose_name_plural': 'Project Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
