# Generated by Django 5.2.1 on 2025-11-15 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=100)),
                ('address', models.CharField(help_text="Customer's address", max_length=100)),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20)),
                ('company', models.CharField(blank=True, help_text='Optional company name', max_length=100)),
                ('team', models.CharField(choices=[('support', 'Support')], help_text='Team responsible for this customer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this customer record', on_delete=django.db.models.deletion.CASCADE, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Detail',
                'verbose_name_plural': 'Customer Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerdetailedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('support', 'Support')], default='support', help_text="Defines the user's role in customer operations", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customerdetailed_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Role Profile',
                'verbose_name_plural': 'Customer Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
