# Generated by Django 5.2.1 on 2025-12-22 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('resource', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_date_pr', models.DateField()),
                ('requisition_no', models.CharField(max_length=50)),
                ('resource_unit_pr', models.CharField(blank=True, max_length=200)),
                ('quantity_pr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_date_pr', models.DateField()),
                ('remarks', models.CharField(max_length=50)),
                ('team', models.CharField(choices=[('se', 'SE')], help_text='Team responsible for this pr', max_length=50)),
                ('allow_team_edit', models.BooleanField(default=False, help_text='If True, allows the team member who created this record to edit/delete it')),
                ('edit_request_pending', models.BooleanField(default=False, help_text='If True, indicates the team member has requested edit/delete access')),
                ('submitted_for_approval', models.BooleanField(default=False, help_text='Checked when user sends this PR to admin for approval')),
                ('admin_approved', models.BooleanField(default=False, help_text='Admin approval status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated')),
                ('created_by', models.ForeignKey(help_text='User who created this pr record', on_delete=django.db.models.deletion.CASCADE, related_name='created_prs', to=settings.AUTH_USER_MODEL)),
                ('project_name_pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_project_name_pr', to='project.project', verbose_name='Project Name')),
                ('resource_name_pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_resource_name_pr', to='resource.resource', verbose_name='Resource Name')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this pr record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pr Detail',
                'verbose_name_plural': 'Pr Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('se', 'SE')], default='se', help_text="Defines the user's role in pr management", max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pr_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pr Role Profile',
                'verbose_name_plural': 'Pr Role Profiles',
                'ordering': ['user__username'],
            },
        ),
    ]
